my_scalar: my_scalar.o scalar_product.o
	gcc my_scalar.o scalar_product.o -o my_scalar

my_scalar.o: my_scalar.c
	gcc -c my_scalar.c -Wall -ansi -pedantic -o my_scalar.o

scalar_product.o: scalar_product.c
	gcc -c scalar_product.c -Wall -ansi -pedantic -o scalar_product.o