find_bits: find_bits.o get_on_bits.o
	gcc find_bits.o get_on_bits.o -o find_bits


find_bits.o: find_bits.c
	gcc -c find_bits.c -Wall -ansi -pedantic -o find_bits.o


get_on_bits.o: get_on_bits.c
	gcc -c get_on_bits.c -Wall -ansi -pedantic -o get_on_bits.o